sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-itcast-cwj
    access-key-secret: ZcJnyLAAwj7qROSpItFt39nSvFxcQm
    access-key-id: LTAI5t8FDJL6Gcgv8R6d7B4y

